[project]
name = "Decentralized-Identity-Verification"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.Decentralized-Identity-Verification-Contract]
path = "contracts/Decentralized-Identity-Verification-Contract.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
